packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  # React Ecosystem
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0

  # Build Tools
  typescript: ^5.8.0
  vite: ^6.0.5
  '@vitejs/plugin-react-swc': ^3.5.0
  
  # Testing
  vitest: ^3.0.1
  vitest-browser-react: ^0.2.0
  '@vitest/ui': ^3.0.7
  '@vitest/browser': ^3.0.1
  '@vitest/coverage-v8': ^3.0.1
  playwright: ^1.49.1

  # Styling & UI
  tailwindcss: ^4.0.0
  '@tailwindcss/postcss': ^4.0.0
  '@tailwindcss/vite': ^4.0.3
  tailwind-merge: ^3.3.0
  tw-animate-css: ^1.2.5
  postcss: ^8.5.1

  # Radix UI Components
  '@radix-ui/react-dialog': ^1.1.6
  '@radix-ui/react-dropdown-menu': ^2.1.6
  '@radix-ui/react-label': ^2.1.2
  '@radix-ui/react-navigation-menu': ^1.2.6
  '@radix-ui/react-separator': ^1.1.3
  '@radix-ui/react-slot': ^1.1.2

  # Other UI Libraries
  next-themes: ^0.4.6
  sonner: ^2.0.1
  vaul: ^1.1.2

  # Form Handling
  '@hookform/resolvers': ^5.1.0
  react-hook-form: ^7.54.2

  # State Management & Routing
  '@tanstack/react-query': ^5.66.0
  '@tanstack/react-router': ^1.102.1
  '@tanstack/react-query-devtools': ^5.66.0
  '@tanstack/react-router-devtools': ^1.114.34
  '@tanstack/router-plugin': ^1.102.2

  # Utilities
  clsx: ^2.1.1
  class-variance-authority: ^0.7.1
  cmdk: ^1.1.1
  lucide-react: ^0.513.0
  zod: ^3.24.2
  
  # API & HTTP
  axios: ^1.7.9

  # Development Tools
  '@biomejs/biome': ^1.9.4
  msw: ^2.7.0

  # Storybook
  storybook: ^9.0.6
  '@chromatic-com/storybook': ^4.0.0
  '@storybook/addon-a11y': ^9.0.6
  '@storybook/addon-actions': ^9.0.6
  '@storybook/addon-essentials': ^8.6.4
  '@storybook/addon-themes': ^9.0.6
  '@storybook/blocks': ^8.6.4
  '@storybook/experimental-addon-test': ^8.6.4
  '@storybook/react': ^9.0.6
  '@storybook/react-vite': ^9.0.6
  '@storybook/test': ^8.6.4
  
  # Node Types
  '@types/node': ^22.13.1

catalogDefault:
  # Internal workspace packages always use workspace protocol
  '@vite-react-ts/ui': 'workspace:*'
  '@vite-react-ts/utils': 'workspace:*'
  '@vite-react-ts/config': 'workspace:*'
  '@vite-react-ts/api': 'workspace:*'