packages:
  - apps/*
  - configs/*
  - packages/*
  - tools/*

catalog:
  '@biomejs/biome': 2.1.1
  '@chromatic-com/storybook': ^4.0.0
  '@hookform/resolvers': ^5.1.1
  '@manypkg/cli': ^0.24.0
  '@radix-ui/react-accordion': ^1.2.11
  '@radix-ui/react-alert-dialog': ^1.1.14
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.2
  '@radix-ui/react-collapsible': ^1.1.11
  '@radix-ui/react-context-menu': ^2.2.15
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': 2.1.15
  '@radix-ui/react-hover-card': ^1.1.14
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.15
  '@radix-ui/react-navigation-menu': 1.2.13
  '@radix-ui/react-popover': ^1.1.14
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.7
  '@radix-ui/react-scroll-area': ^1.2.9
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.5
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-toggle': ^1.1.9
  '@radix-ui/react-toggle-group': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.7
  '@storybook/addon-a11y': ^9.0.15
  '@storybook/addon-docs': ^9.0.15
  '@storybook/addon-themes': ^9.0.15
  '@storybook/addon-vitest': ^9.0.15
  '@storybook/builder-vite': ^9.0.15
  '@storybook/react-vite': ^9.0.15
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-query': ^5.66.0
  '@tanstack/react-router': ^1.102.1
  '@tanstack/react-query-devtools': ^5.66.0
  '@tanstack/react-router-devtools': ^1.114.34
  '@tanstack/router-plugin': ^1.102.2
  '@types/node': ^24.0.12
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react-swc': ^3.10.2
  '@vitest/ui': ^3.2.4
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  axios: ^1.7.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  embla-carousel-react: ^8.6.0
  input-otp: ^1.4.2
  lucide-react: ^0.525.0
  msw: ^2.7.0
  next-themes: ^0.4.6
  playwright: ^1.53.2
  postcss: ^8.5.6
  react: ^19.1.0
  react-day-picker: ^9.8.0
  react-dom: ^19.1.0
  react-hook-form: ^7.60.0
  react-resizable-panels: ^3.0.3
  sonner: ^2.0.6
  storybook: ^9.0.15
  style-dictionary: 5.0.1
  syncpack: ^13.0.4
  tailwindcss: ^4.1.11
  tailwind-merge: ^3.3.1
  tailwind-variants: ^1.0.0
  tsdown: ^0.12.9
  tw-animate-css: ^1.3.5
  typescript: ^5.8.3
  vaul: ^1.1.2
  vite: ^7.0.3
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
  vitest-browser-react: ^1.0.0
  zod: ^3.25.74

onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - style-dictionary
