packages:
  - apps/*
  - configs/*
  - packages/*
  - tools/*

catalog:
  '@biomejs/biome': 2.0.6
  '@chromatic-com/storybook': ^4.0.0
  '@hookform/resolvers': ^5.1.1
  '@manypkg/cli': ^0.24.0
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-navigation-menu': ^1.2.13
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@storybook/addon-a11y': ^9.0.15
  '@storybook/addon-docs': ^9.0.15
  '@storybook/addon-themes': ^9.0.15
  '@storybook/addon-vitest': ^9.0.15
  '@storybook/builder-vite': ^9.0.15
  '@storybook/react-vite': ^9.0.15
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-query': ^5.66.0
  '@tanstack/react-router': ^1.102.1
  '@tanstack/react-query-devtools': ^5.66.0
  '@tanstack/react-router-devtools': ^1.114.34
  '@tanstack/router-plugin': ^1.102.2
  '@types/node': ^24.0.10
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react-swc': ^3.10.2
  '@vitest/ui': ^3.2.4
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  axios: ^1.7.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  lucide-react: ^0.525.0
  msw: ^2.7.0
  next-themes: ^0.4.6
  playwright: ^1.53.2
  postcss: ^8.5.6
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hook-form: ^7.59.0
  sonner: ^2.0.6
  storybook: ^9.0.15
  syncpack: ^13.0.4
  tailwindcss: ^4.1.11
  tailwind-merge: ^3.3.1
  tw-animate-css: ^1.3.5
  typescript: ^5.8.3
  vaul: ^1.1.2
  vite: ^7.0.1
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
  vitest-browser-react: ^1.0.0
  zod: ^3.24.2

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
