packages:
  - 'apps/*'
  - 'packages/*'
  - 'configs/*'
  - 'tools/*'

catalog:
  '@biomejs/biome': 2.0.5
  '@chromatic-com/storybook': ^4.0.0
  '@hookform/resolvers': ^5.1.0
  '@radix-ui/react-dialog': ^1.1.6
  '@radix-ui/react-dropdown-menu': ^2.1.6
  '@radix-ui/react-label': ^2.1.2
  '@radix-ui/react-navigation-menu': ^1.2.6
  '@radix-ui/react-separator': ^1.1.3
  '@radix-ui/react-slot': ^1.1.2
  '@storybook/addon-a11y': ^9.0.6
  '@storybook/addon-docs': ^9.0.6
  '@storybook/addon-themes': ^9.0.6
  '@storybook/addon-vitest': ^9.0.6
  '@storybook/react-vite': ^9.0.6
  '@tailwindcss/postcss': ^4.0.0
  '@tailwindcss/vite': ^4.0.3
  '@tanstack/react-query': ^5.66.0
  '@tanstack/react-router': ^1.102.1
  '@tanstack/react-query-devtools': ^5.66.0
  '@tanstack/react-router-devtools': ^1.114.34
  '@tanstack/router-plugin': ^1.102.2
  '@types/node': ^22.13.1
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@vitejs/plugin-react-swc': ^3.5.0
  '@vitest/ui': ^3.0.7
  '@vitest/browser': ^3.0.1
  '@vitest/coverage-v8': ^3.0.1
  axios: ^1.7.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  lucide-react: ^0.514.0
  msw: ^2.7.0
  next-themes: ^0.4.6
  playwright: ^1.49.1
  postcss: ^8.5.1
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hook-form: ^7.54.2
  sonner: ^2.0.1
  storybook: ^9.0.6
  tailwindcss: ^4.0.0
  tailwind-merge: ^3.3.0
  tw-animate-css: ^1.2.5
  typescript: ^5.8.0
  vaul: ^1.1.2
  vite: ^6.0.5
  vitest: ^3.0.1
  vitest-browser-react: ^0.2.0
  zod: ^3.24.2

catalogDefault:
  # Internal workspace packages always use workspace protocol
  '@vite-react-ts/ui': 'workspace:*'
  '@vite-react-ts/utils': 'workspace:*'
  '@vite-react-ts/config': 'workspace:*'
  '@vite-react-ts/api': 'workspace:*'